Repository cloudnode-pro/BankAccounts, pull requests merged in 2023-11, with the labels that each got.

#41 Fix POS full double chest unexpected behaviour
  src/main/java/pro/cloudnode/smp/bankaccounts/BankAccounts.java
  src/main/java/pro/cloudnode/smp/bankaccounts/POS.java
  src/main/java/pro/cloudnode/smp/bankaccounts/commands/BankCommand.java
  src/main/java/pro/cloudnode/smp/bankaccounts/events/GUI.java
  src/main/java/pro/cloudnode/smp/bankaccounts/events/PlayerInteract.java
  src/main/resources/config.yml
Labels: bug

#47 Fix update checking failling on an unsupported server version
  src/main/java/pro/cloudnode/smp/bankaccounts/BankAccounts.java
Labels: bug, simple

#56 Use SQLite that comes with paper instead of shading
  pom.xml
  src/main/java/pro/cloudnode/smp/bankaccounts/BankAccounts.java
Labels: enhancement

#61 Config and permissions refactor
  src/main/java/pro/cloudnode/smp/bankaccounts/Account.java
  src/main/java/pro/cloudnode/smp/bankaccounts/BankAccounts.java
  src/main/java/pro/cloudnode/smp/bankaccounts/BankConfig.java
  src/main/java/pro/cloudnode/smp/bankaccounts/Command.java
  src/main/java/pro/cloudnode/smp/bankaccounts/POS.java
  src/main/java/pro/cloudnode/smp/bankaccounts/Permissions.java
  src/main/java/pro/cloudnode/smp/bankaccounts/commands/BankCommand.java
  src/main/java/pro/cloudnode/smp/bankaccounts/commands/POSCommand.java
  src/main/java/pro/cloudnode/smp/bankaccounts/events/BlockBreak.java
  src/main/java/pro/cloudnode/smp/bankaccounts/events/GUI.java
  src/main/java/pro/cloudnode/smp/bankaccounts/events/Join.java
  src/main/java/pro/cloudnode/smp/bankaccounts/events/PlayerInteract.java
  src/main/resources/config.yml
Labels: enhancement
